In [1]:
# Importing all the necessary libraries
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

In [2]:
df = pd.read_csv("Precily_Text_Similarity.csv")
df

,text1,text2
0,broadband challenges tv viewing the number of ...,gardener wins double in glasgow britain s jaso...
1,rap boss arrested over drug find rap mogul mar...,amnesty chief laments war failure the lack of ...
2,player burn-out worries robinson england coach...,hanks greeted at wintry premiere hollywood sta...
3,hearts of oak 3-2 cotonsport hearts of oak set...,redford s vision of sundance despite sporting ...
4,sir paul rocks super bowl crowds sir paul mcca...,mauresmo opens with victory in la amelie maure...
...,...,...
2995,uk directors guild nominees named martin scors...,steel firm to cut 45 000 jobs mittal steel ...
2996,u2 to play at grammy awards show irish rock ba...,israel looks to us for bank chief israel has a...
2997,pountney handed ban and fine northampton coach...,india and iran in gas export deal india has si...
2998,belle named best scottish band belle & sebas...,mido makes third apology ahmed mido hossam h...
2999,criminal probe on citigroup deals traders at u...,former ni minister scott dies former northern ...

In [3]:
# Getting text values
text1 = df["text1"].values
text2 = df["text2"].values

# Loading Sentence Embedding Model
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

# Calculating Semantic Similarities between sentences 
base_sim = []
for i in range(len(text1[:10])):
    embeddings = model.encode([text1[i], text2[i]])
    base_sim.append(cosine_similarity(embeddings[0].reshape(1, -1), embeddings[1].reshape(1, -1))[0][0])

In [6]:
# Assigning calculated similarity in new column
df["similarity"] = base_sim
df.head(10)

,text1,text2,similarity
0,broadband challenges tv viewing the number of ...,gardener wins double in glasgow britain s jaso...,0.035034
1,rap boss arrested over drug find rap mogul mar...,amnesty chief laments war failure the lack of ...,0.184137
2,player burn-out worries robinson england coach...,hanks greeted at wintry premiere hollywood sta...,0.079289
3,hearts of oak 3-2 cotonsport hearts of oak set...,redford s vision of sundance despite sporting ...,-0.109606
4,sir paul rocks super bowl crowds sir paul mcca...,mauresmo opens with victory in la amelie maure...,0.055282
5,india to deport bollywood actress india has or...,fosters buys stake in winemaker australian bre...,-0.071038
6,mutant book wins guardian prize a book about t...,jp morgan admits us slavery links thousands of...,0.071058
7,aids and climate top davos agenda climate chan...,howl helps boost japan s cinemas japan s box o...,-0.002455
8,kennedy predicts bigger turnout voters pent ...,ocean s twelve raids box office ocean s twelve...,-0.039513
9,carry on star patsy rowlands dies actress pats...,uk broadband gets speed injection broadband s ...,0.101950

In [7]:
# Saving the Calculated Similarity Results
df.to_csv("Results_Precily_Text_Similarity.csv")